[package]
name = "compile_to_rout"
version = "0.1.0"
authors = ["W-A-James <wajames@princeton.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
clap = "2.33.3"
